// Code generated by shiftgen at shift.go:8. DO NOT EDIT.

package playerMatch

import (
	"context"
	"database/sql"
	"strings"
	"time"
	"github.com/luno/jettison/errors"
	"github.com/luno/jettison/j"
	"github.com/luno/shift"
)

// Insert inserts a new player_match table entity. All the fields of the 
// create receiver are set, as well as status, created_at and updated_at. 
// The newly created entity id is returned on success or an error.
func (一 create) Insert(ctx context.Context, tx *sql.Tx,st shift.Status) (int64, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	q.WriteString("insert into player_match set `status`=?, `created_at`=?, `updated_at`=? ")
	args = append(args, st.Enum(), time.Now(), time.Now())

	q.WriteString(", `match`=?")
	args = append(args, 一.Match)

	q.WriteString(", `player_name`=?")
	args = append(args, 一.PlayerName)

	res, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return 0, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return 0, err
	}

	return id, nil
}

// Update updates the status of a player_match table entity. All the fields of the
// round receiver are updated, as well as status and updated_at. 
// The entity id is returned on success or an error.
func (一 round) Update(ctx context.Context, tx *sql.Tx,from shift.Status, 
	to shift.Status) (int64, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	q.WriteString("update player_match set `status`=?, `updated_at`=? ")
	args = append(args, to.Enum(), time.Now())

	q.WriteString(", `rank`=?")
	args = append(args, 一.Rank)

	q.WriteString(", `my_part`=?")
	args = append(args, 一.MyPart)

	q.WriteString(", `player_part`=?")
	args = append(args, 一.PlayerPart)

	q.WriteString(" where `id`=? and `status`=?")
	args = append(args, 一.ID, from.Enum())

	res, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return 0, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	if n != 1 {
		return 0, errors.Wrap(shift.ErrRowCount, "round", j.KV("count", n))
	}

	return 一.ID, nil
}
