// Code generated by protoc-gen-go. DO NOT EDIT.
// source: teamteam.proto

package teamteampb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import reflexpb "github.com/luno/reflex/reflexpb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_teamteam_e3048e0a75a105c9, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetPlayerRoundRequest struct {
	Round                int32    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Player               string   `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerRoundRequest) Reset()         { *m = GetPlayerRoundRequest{} }
func (m *GetPlayerRoundRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerRoundRequest) ProtoMessage()    {}
func (*GetPlayerRoundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_teamteam_e3048e0a75a105c9, []int{1}
}
func (m *GetPlayerRoundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerRoundRequest.Unmarshal(m, b)
}
func (m *GetPlayerRoundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerRoundRequest.Marshal(b, m, deterministic)
}
func (dst *GetPlayerRoundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerRoundRequest.Merge(dst, src)
}
func (m *GetPlayerRoundRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerRoundRequest.Size(m)
}
func (m *GetPlayerRoundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerRoundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerRoundRequest proto.InternalMessageInfo

func (m *GetPlayerRoundRequest) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *GetPlayerRoundRequest) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

type PlayerRound struct {
	PlayerRank           int32    `protobuf:"varint,1,opt,name=player_rank,json=playerRank,proto3" json:"player_rank,omitempty"`
	MyPart               int32    `protobuf:"varint,2,opt,name=my_part,json=myPart,proto3" json:"my_part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerRound) Reset()         { *m = PlayerRound{} }
func (m *PlayerRound) String() string { return proto.CompactTextString(m) }
func (*PlayerRound) ProtoMessage()    {}
func (*PlayerRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_teamteam_e3048e0a75a105c9, []int{2}
}
func (m *PlayerRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerRound.Unmarshal(m, b)
}
func (m *PlayerRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerRound.Marshal(b, m, deterministic)
}
func (dst *PlayerRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerRound.Merge(dst, src)
}
func (m *PlayerRound) XXX_Size() int {
	return xxx_messageInfo_PlayerRound.Size(m)
}
func (m *PlayerRound) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerRound.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerRound proto.InternalMessageInfo

func (m *PlayerRound) GetPlayerRank() int32 {
	if m != nil {
		return m.PlayerRank
	}
	return 0
}

func (m *PlayerRound) GetMyPart() int32 {
	if m != nil {
		return m.MyPart
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "teamteampb.Empty")
	proto.RegisterType((*GetPlayerRoundRequest)(nil), "teamteampb.GetPlayerRoundRequest")
	proto.RegisterType((*PlayerRound)(nil), "teamteampb.PlayerRound")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeamTeamClient is the client API for TeamTeam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeamTeamClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stream(ctx context.Context, in *reflexpb.StreamRequest, opts ...grpc.CallOption) (TeamTeam_StreamClient, error)
	GetPlayerRound(ctx context.Context, in *GetPlayerRoundRequest, opts ...grpc.CallOption) (*PlayerRound, error)
}

type teamTeamClient struct {
	cc *grpc.ClientConn
}

func NewTeamTeamClient(cc *grpc.ClientConn) TeamTeamClient {
	return &teamTeamClient{cc}
}

func (c *teamTeamClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/teamteampb.TeamTeam/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamTeamClient) Stream(ctx context.Context, in *reflexpb.StreamRequest, opts ...grpc.CallOption) (TeamTeam_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TeamTeam_serviceDesc.Streams[0], "/teamteampb.TeamTeam/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &teamTeamStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TeamTeam_StreamClient interface {
	Recv() (*reflexpb.Event, error)
	grpc.ClientStream
}

type teamTeamStreamClient struct {
	grpc.ClientStream
}

func (x *teamTeamStreamClient) Recv() (*reflexpb.Event, error) {
	m := new(reflexpb.Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *teamTeamClient) GetPlayerRound(ctx context.Context, in *GetPlayerRoundRequest, opts ...grpc.CallOption) (*PlayerRound, error) {
	out := new(PlayerRound)
	err := c.cc.Invoke(ctx, "/teamteampb.TeamTeam/GetPlayerRound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamTeamServer is the server API for TeamTeam service.
type TeamTeamServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	Stream(*reflexpb.StreamRequest, TeamTeam_StreamServer) error
	GetPlayerRound(context.Context, *GetPlayerRoundRequest) (*PlayerRound, error)
}

func RegisterTeamTeamServer(s *grpc.Server, srv TeamTeamServer) {
	s.RegisterService(&_TeamTeam_serviceDesc, srv)
}

func _TeamTeam_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamTeamServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teamteampb.TeamTeam/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamTeamServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamTeam_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(reflexpb.StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TeamTeamServer).Stream(m, &teamTeamStreamServer{stream})
}

type TeamTeam_StreamServer interface {
	Send(*reflexpb.Event) error
	grpc.ServerStream
}

type teamTeamStreamServer struct {
	grpc.ServerStream
}

func (x *teamTeamStreamServer) Send(m *reflexpb.Event) error {
	return x.ServerStream.SendMsg(m)
}

func _TeamTeam_GetPlayerRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamTeamServer).GetPlayerRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teamteampb.TeamTeam/GetPlayerRound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamTeamServer).GetPlayerRound(ctx, req.(*GetPlayerRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeamTeam_serviceDesc = grpc.ServiceDesc{
	ServiceName: "teamteampb.TeamTeam",
	HandlerType: (*TeamTeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TeamTeam_Ping_Handler,
		},
		{
			MethodName: "GetPlayerRound",
			Handler:    _TeamTeam_GetPlayerRound_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _TeamTeam_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "teamteam.proto",
}

func init() { proto.RegisterFile("teamteam.proto", fileDescriptor_teamteam_e3048e0a75a105c9) }

var fileDescriptor_teamteam_e3048e0a75a105c9 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x4d, 0xc4, 0xa4, 0x3a, 0x85, 0x8a, 0x83, 0x9a, 0x92, 0x8b, 0x75, 0x4f, 0x3d, 0xc8, 0x56,
	0x14, 0xfc, 0x83, 0xd0, 0x9b, 0x84, 0xd5, 0x7b, 0xd9, 0xe8, 0x5a, 0x4b, 0xb3, 0x9b, 0x75, 0x9d,
	0x88, 0xf9, 0x3d, 0xbf, 0x4c, 0x92, 0x6c, 0x69, 0x44, 0x0f, 0x43, 0xf2, 0xde, 0x9b, 0x79, 0xec,
	0x7b, 0x30, 0x21, 0x25, 0x75, 0x3b, 0xdc, 0xba, 0x8a, 0x2a, 0x84, 0x1d, 0xb6, 0x45, 0x7a, 0xbd,
	0xde, 0xd0, 0x5b, 0x5d, 0xf0, 0xe7, 0x4a, 0x2f, 0xca, 0xda, 0x54, 0x0b, 0xa7, 0x5e, 0x4b, 0xf5,
	0xe5, 0x3f, 0xb6, 0xf0, 0x3f, 0xfd, 0x25, 0x1b, 0x41, 0x94, 0x69, 0x4b, 0x0d, 0xcb, 0xe0, 0x7c,
	0xa9, 0x28, 0x2f, 0x65, 0xa3, 0x9c, 0xa8, 0x6a, 0xf3, 0x22, 0xd4, 0x7b, 0xad, 0x3e, 0x08, 0xcf,
	0x20, 0x72, 0x2d, 0x9e, 0x86, 0xb3, 0x70, 0x1e, 0x89, 0x1e, 0xe0, 0x05, 0xc4, 0xb6, 0xdb, 0x9d,
	0x1e, 0xcc, 0xc2, 0xf9, 0xb1, 0xf0, 0x88, 0x2d, 0x61, 0x3c, 0xf0, 0xc0, 0x4b, 0x18, 0xf7, 0xc2,
	0xca, 0x49, 0xb3, 0xf5, 0x16, 0xd0, 0x53, 0x42, 0x9a, 0x2d, 0x26, 0x30, 0xd2, 0xcd, 0xca, 0x4a,
	0x47, 0x9d, 0x51, 0x24, 0x62, 0xdd, 0xe4, 0xd2, 0xd1, 0xed, 0x77, 0x08, 0x47, 0x4f, 0x4a, 0xea,
	0x76, 0x90, 0xc3, 0x61, 0xbe, 0x31, 0x6b, 0x3c, 0xe5, 0xfb, 0xa0, 0xbc, 0x7b, 0x77, 0xfa, 0x97,
	0x62, 0x01, 0xde, 0x43, 0xfc, 0x48, 0xae, 0xbd, 0x4c, 0xf8, 0x2e, 0x37, 0xef, 0x19, 0x1f, 0x2b,
	0x3d, 0xd9, 0x0b, 0xd9, 0xa7, 0x32, 0xc4, 0x82, 0x9b, 0x10, 0x1f, 0x60, 0xf2, 0xbb, 0x04, 0xbc,
	0x1a, 0xda, 0xff, 0x5b, 0x50, 0x9a, 0x0c, 0x57, 0x06, 0x3a, 0x0b, 0x8a, 0xb8, 0x2b, 0xf9, 0xee,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xbb, 0xad, 0x43, 0xb0, 0x01, 0x00, 0x00,
}
