package ops

// Code generated by genbackendsimpl. DO NOT EDIT.

import (
	"testing"

	"github.com/corverroos/unsure/engine"
)

type backendsImpl struct {
	engineClient engine.Client
}

func MakeBackends(
	engineClient engine.Client,
) *backendsImpl {
	return &backendsImpl{
		engineClient: engineClient,
	}
}

type backendsOption func(*backendsImpl)

func NewBackendsForTesting(tb testing.TB, opts ...backendsOption) *backendsImpl {
	var b backendsImpl
	for _, opt := range opts {
		opt(&b)
	}
	return &b
}

func WithEngineClient(engineClient engine.Client) backendsOption {
	return func(b *backendsImpl) {
		b.engineClient = engineClient
	}
}

func (b *backendsImpl) EngineClient() engine.Client {
	if b == nil {
		return nil
	}
	return b.engineClient
}
